language: node_js
os:
  - osx
  - linux
node_js:
  - "6"
env:
  - FULL_CHECK=false
  - FULL_CHECK=true
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - node_modules
matrix:
  allow_failures:
    - env: FULL_CHECK=true
before_script:
  - npm install
  - npm install -g license-checker
script:
  - if [[ $(license-checker --production --exclude '(GPL-2.0 OR MIT)' | grep GPL) ]]; then license-checker --production | grep -C 1 GPL && false; fi
  - npm run build
  - if [[ $FULL_CHECK == "true" ]]; then npm run lint --silent; fi
  - npm run dist
