os: Visual Studio 2015
cache:
  - node_modules
environment:
  # GCP_PASSWD:
  #   secure: erzLJz7qT0kCJa+jZG6Sf9wwkfLYO2UDLzydkKTdwqA=
  matrix:
    - nodejs_version: 6
install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%
  # Set up version from git tags.
  # - git describe --tags --always > version.txt
  # - sed -E 's/v([[:digit:]]+\.[[:digit:]]+)\.[[:digit:]]-([[:digit:]]+)-g([a-f0-9]+)/v\1.\2+\3/' version.txt > version-app.txt
  # - sed -E 's/v([[:digit:]]+\.[[:digit:]]+)\.[[:digit:]]-([[:digit:]]+).+/v\1.\2/' version.txt > version-only.txt
  # - sed -E 's/v([[:digit:]]+\.[[:digit:]]+)\.[[:digit:]]-([[:digit:]]+).+/v\1.x/' version.txt > version-base.txt
  # - set /p VERSION=<version-app.txt
  # - set /p APP_VERSION_GIT_TAG=<version-app.txt
  # - set /p VERSION_ONLY=<version-only.txt
  # - set /p VERSION_BASE=<version-base.txt
  # - echo %VERSION_BASE% %VERSION_ONLY% %VERSION%

  # Install janus.
  - curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get-windows.sh | bash
  - set PATH=./janusbin;%PATH%
  - ps: $env:APP_VERSION_GIT_TAG = "$(janus version -format TAG_OR_NIGHTLY)"

  # Set up build dependencies.
  - ps: Install-Product node $end:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - bash ./dependencies.sh
build: off
version: '{build}'
test_script:
  - npm run dist
artifacts:
  - path: './dist/*.exe'
    name: emerald-wallet
deploy_script:
  - ps: >-
      If ($env:APPVEYOR_REPO_BRANCH -eq 'master') {
          bash ./gcloud-deploy.sh
      }
